### ISSUE TITLE
forcing disable breaks Dummy application

### ISSUE THREAD

**Issue by ksnyde** [rwjblue/ember-disable-prototype-extensions#1]
I like the idea of this but when after ensuring that all of my code indeed was "prototype free" I noticed that my Dummy test app was running into errors which were prototype based but more "core ember" stuff rather than my own code. As an example, ember-debug's `sourceMapCache` uses prototype extensions. 

I've had to pull this out of my Addon development for now as it was causing too many problems but it would be nice to see some way to force the exclusion on prototypes to just the addon (and not core Ember stuff) if that's possible. Not sure it is.

**Comment by rwjblue** [comment]
The bug in the inspector was fixed in https://github.com/emberjs/ember-inspector/pull/316, and Teddy mentioned in that thread that he was planning on releasing a new version this weekend.

**Comment by ksnyde** [comment]
ok great, thanks @rwjblue
