### ISSUE TITLE
[QUESTION] how do I remove .on('init')?

### ISSUE THREAD

**Issue by williamsbdev** [rwjblue/ember-disable-prototype-extensions#2]
I am trying to get my addon updated to not use any of the prototype extensions. One that I'm having trouble with is the `.on('init')` extension. How do I go about removing this so that I can still perform the needed functionality?

**Comment by rwjblue** [comment]
```
import Ember from 'ember';

var on = Ember.on;

export default Ember.Object.extend({
  doStuffOnInit: on('init', function() {
    // your stuff here
  })
});
```

**Comment by williamsbdev** [comment]
Thank you! I was struggling with this for a while and then finally tried one more thing that worked (however I didn't like it), so now I'm taking your suggestion as yours is much cleaner.
